name = "HouLean"
version = "0.1.0"
defaultTargets = ["houlean"]
testDriver = "Tests"

[[lean_lib]]
name = "HouLean"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "houlean"
root = "Main"
supportInterpreter = true
moreLinkArgs = ["-s", "-flto", "-Wl,--gc-sections", "-Wl,--as-needed"]

[[lean_exe]]
name = "compileToApexGraph"
root = "CompileToApexGraph"
supportInterpreter = true

[[lean_exe]]
name = "exportTypes"
root = "ExportTypes"
supportInterpreter = true

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4"
rev = "v4.25.0"