name = "HouLean"
version = "0.1.0"
defaultTargets = ["houlean"]

[[lean_lib]]
name = "HouLean"
buildType = "debug"

[[lean_exe]]
name = "houlean"
root = "Main"
supportInterpreter = true
buildType = "debug"

[[lean_exe]]
name = "compileToApexGraph"
root = "CompileToApexGraph"
supportInterpreter = true

[[lean_exe]]
name = "exportTypes"
root = "ExportTypes"
supportInterpreter = true

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4"
rev = "v4.24.0"